version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.54.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitor

  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - monitor

  grafana:
    image: grafana/grafana:11.1.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitor
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
      - ./grafana/provisioning/grafana.ini:/etc/grafana/grafana.ini:ro

networks:
  monitor:
    driver: bridge
